@echo off
:: ==============================================================================
:: STEP 5: REMOTE BACKUP SCRIPT
:: ==============================================================================
:: This script connects to the Raspberry Pi over the local network using SCP/SSH.
:: Its purpose is to download all CSV files generated by the monitoring script
:: to the local computer (Windows) as a backup.
:: If the download is successful, it deletes the original files on the Raspberry to free up space.

:: Set the console to UTF-8 mode to read accents properly
chcp 65001 > nul 

echo ===================================================
echo   DATA EXTRACTION - PREDICTIVE MAINTENANCE
echo ===================================================

set DESTINATION_FOLDER="C:\Path\To\Your\Folder\Data_Backups"

:: 1. Create the backup folder if it does not exist
if not exist %DESTINATION_FOLDER% mkdir %DESTINATION_FOLDER%

echo [1/3] Downloading CSV histories from the Raspberry Pi...
scp your_user@your_ip:/home/your_user/*.csv %DESTINATION_FOLDER%

:: 2. SECURITY CHECK (errorlevel 0 means scp worked perfectly)
if %errorlevel% equ 0 (
    echo [2/3] Download perfect. Cleaning the SD card memory...
    ssh your_user@your_ip "rm /home/your_user/*.csv"
    echo [3/3] Process completed successfully!
) else (
    echo [!] NETWORK ERROR: Could not copy. Data is still safe on the board.
)

:: The script will close itself in 10 seconds
timeout /t 10