"""
==============================================================================
UTILITY: TELEGRAM ALERTS MODULE
==============================================================================
- Purpose: Contains a reusable function `send_telegram_alert` that can be
  imported and used by any other script in the project to send notifications
  to a specific Telegram chat.
==============================================================================
"""
import requests

def send_telegram_alert(message):
    """
    Sends a text message through a Telegram bot.
    
    Parameters:
    message (str): The text with the alert or information to be sent to the specified chat.
    """
    TOKEN = 'your_token_here'
    CHAT_ID = 'your_chat_id_here'
    
    # Build the Telegram API URL
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    
    # Prepare the message data
    payload = {
        "chat_id": CHAT_ID,
        "text": message,
        "parse_mode": "Markdown"
    }
    
    # Send the request
    try:
        response = requests.post(url, data=payload)
        if response.status_code == 200:
            print("✅ Message successfully sent to Telegram.")
        else:
            print(f"❌ Error sending. Code: {response.status_code}")
            
    except Exception as e:
        print(f"❌ Exception connecting to Telegram: {e}")

# --- SYSTEM TEST ---
if __name__ == "__main__":
    # Imagine this is the message generated by your Isolation Forest upon detecting a -1
    alarm_message = "🚨 *MAINTENANCE ALERT* 🚨\n\nAnomalous behavior detected in the fan (Possible imbalance).\n\nReview required."
    send_telegram_alert(alarm_message)